<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net462;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>UniversalEncoding.Demo</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <NoWarn></NoWarn>
    <Authors>JavaCommons</Authors>
    <Company>JavaCommons Technologies</Company>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <!--
  <PropertyGroup>
    <StartupObject>Demo.Program</StartupObject>
  </PropertyGroup>
  -->
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Linq" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EasyObject" Version="2026.402.2005.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UniversalEncoding\UniversalEncoding.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="assets\**">
      <Link>assets\%(RecursiveDir)\%(Filename)%(Extension)</Link>
      <TargetPath>assets\%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>